// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// app/layout.tsx
import "./globals.css";
import AsciiGradientField from "@/components/CodexSplash";
import TopBar from "@/components/TopBar";

export const metadata = { title: "Your Name", description: "Personal site" };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="bg-black">
      <body className="min-h-screen text-neutral-200">
        {/* site-wide background */}
        <AsciiGradientField
          className="z-0 pointer-events-none" // sits behind everything & doesn't block clicks
          scale={0.10}
          speed={1.1}
        />

        {/* overlay nav */}
        <TopBar />

        {/* page content */}
        <main className="relative pt-16"> {/* padding makes space under the top bar */}
          {children}
        </main>
      </body>
    </html>
  );
}